# Generated by Django 5.2.6 on 2025-10-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Bayar di Kasir'), ('QRIS', 'QRIS')], default='Cash', max_length=10),
        ),
    ]
