# Generated by Django 5.2.6 on 2025-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_status_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Menunggu Pembayaran'), ('Waiting Confirmation', 'Menunggu Konfirmasi'), ('Paid', 'Lunas'), ('Canceled', 'Dibatalkan')], default='Pending', max_length=25),
        ),
    ]
