# Generated by Django 5.2.6 on 2025-10-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Menunggu Pembayaran'), ('Waiting Confirmation', 'Menunggu Konfirmasi'), ('Paid', 'Lunas'), ('Processing', 'Sedang Disiapkan'), ('Completed', 'Selesai'), ('Canceled', 'Dibatalkan')], default='Pending', max_length=25),
        ),
    ]
